import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalLayout from "../components/layout/ConditionalLayout";
import { Toaster } from "react-hot-toast";
import NotificationsInit from "../components/shared/NotificationInit";
import ToastProvider from "../components/shared/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-[#F2F7FE] relative ${geistSans.variable} ${geistMono.variable}`}
      >
        <ConditionalLayout>{children}</ConditionalLayout>
        <Toaster position="top-right" reverseOrder={false} />
        <NotificationsInit />
        <ToastProvider />
      </body>
    </html>
  );
}
