export const timezoneOptions = [
  // UTC
  { value: "UTC", label: "(UTC+00:00) UTC" },

  // Africa
  { value: "Africa/Abidjan", label: "(UTC+00:00) Abidjan" },
  { value: "Africa/Accra", label: "(UTC+00:00) Accra" },
  { value: "Africa/Algiers", label: "(UTC+01:00) Algiers" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
  { value: "Africa/Casablanca", label: "(UTC+01:00) Casablanca" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) Johannesburg" },
  { value: "Africa/Khartoum", label: "(UTC+02:00) Khartoum" },
  { value: "Africa/Lagos", label: "(UTC+01:00) Lagos" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
  { value: "Africa/Tripoli", label: "(UTC+02:00) Tripoli" },
  { value: "Africa/Tunis", label: "(UTC+01:00) Tunis" },

  // America
  { value: "America/Anchorage", label: "(UTC-09:00) Anchorage" },
  {
    value: "America/Argentina/Buenos_Aires",
    label: "(UTC-03:00) Buenos Aires",
  },
  { value: "America/Bogota", label: "(UTC-05:00) Bogota" },
  { value: "America/Caracas", label: "(UTC-04:00) Caracas" },
  { value: "America/Chicago", label: "(UTC-06:00) Chicago (Central Time)" },
  { value: "America/Denver", label: "(UTC-07:00) Denver (Mountain Time)" },
  { value: "America/Halifax", label: "(UTC-04:00) Halifax" },
  { value: "America/Havana", label: "(UTC-05:00) Havana" },
  { value: "America/Lima", label: "(UTC-05:00) Lima" },
  {
    value: "America/Los_Angeles",
    label: "(UTC-08:00) Los Angeles (Pacific Time)",
  },
  { value: "America/Mexico_City", label: "(UTC-06:00) Mexico City" },
  { value: "America/New_York", label: "(UTC-05:00) New York (Eastern Time)" },
  { value: "America/Panama", label: "(UTC-05:00) Panama" },
  { value: "America/Phoenix", label: "(UTC-07:00) Phoenix" },
  { value: "America/Santiago", label: "(UTC-04:00) Santiago" },
  { value: "America/Sao_Paulo", label: "(UTC-03:00) São Paulo" },
  { value: "America/Toronto", label: "(UTC-05:00) Toronto" },
  { value: "America/Vancouver", label: "(UTC-08:00) Vancouver" },

  // Asia
  { value: "Asia/Almaty", label: "(UTC+06:00) Almaty" },
  { value: "Asia/Amman", label: "(UTC+03:00) Amman" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Baghdad" },
  { value: "Asia/Bahrain", label: "(UTC+03:00) Bahrain" },
  { value: "Asia/Baku", label: "(UTC+04:00) Baku" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok" },
  { value: "Asia/Beirut", label: "(UTC+02:00) Beirut" },
  { value: "Asia/Brunei", label: "(UTC+08:00) Brunei" },
  { value: "Asia/Colombo", label: "(UTC+05:30) Colombo" },
  { value: "Asia/Damascus", label: "(UTC+03:00) Damascus" },
  { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Dubai" },
  { value: "Asia/Gaza", label: "(UTC+02:00) Gaza" },
  { value: "Asia/Ho_Chi_Minh", label: "(UTC+07:00) Ho Chi Minh" },
  { value: "Asia/Hong_Kong", label: "(UTC+08:00) Hong Kong" },
  { value: "Asia/Irkutsk", label: "(UTC+08:00) Irkutsk" },
  { value: "Asia/Istanbul", label: "(UTC+03:00) Istanbul" },
  { value: "Asia/Jakarta", label: "(UTC+07:00) Jakarta" },
  { value: "Asia/Jerusalem", label: "(UTC+02:00) Jerusalem" },
  { value: "Asia/Kabul", label: "(UTC+04:30) Kabul" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Karachi" },
  { value: "Asia/Kathmandu", label: "(UTC+05:45) Kathmandu" },
  { value: "Asia/Kolkata", label: "(UTC+05:30) Kolkata (India)" },
  { value: "Asia/Kuala_Lumpur", label: "(UTC+08:00) Kuala Lumpur" },
  { value: "Asia/Kuwait", label: "(UTC+03:00) Kuwait" },
  { value: "Asia/Manila", label: "(UTC+08:00) Manila" },
  { value: "Asia/Muscat", label: "(UTC+04:00) Muscat" },
  { value: "Asia/Qatar", label: "(UTC+03:00) Qatar" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Riyadh" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) Shanghai (China)" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Singapore" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent" },
  { value: "Asia/Tehran", label: "(UTC+03:30) Tehran" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Tokyo" },
  { value: "Asia/Vladivostok", label: "(UTC+10:00) Vladivostok" },
  { value: "Asia/Yangon", label: "(UTC+06:30) Yangon" },
  { value: "Asia/Yekaterinburg", label: "(UTC+05:00) Yekaterinburg" },

  // Atlantic
  { value: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
  { value: "Atlantic/Reykjavik", label: "(UTC+00:00) Reykjavik" },

  // Australia
  { value: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Brisbane" },
  { value: "Australia/Darwin", label: "(UTC+09:30) Darwin" },
  { value: "Australia/Hobart", label: "(UTC+10:00) Hobart" },
  { value: "Australia/Melbourne", label: "(UTC+10:00) Melbourne" },
  { value: "Australia/Perth", label: "(UTC+08:00) Perth" },
  { value: "Australia/Sydney", label: "(UTC+10:00) Sydney" },

  // Europe
  { value: "Europe/Amsterdam", label: "(UTC+01:00) Amsterdam" },
  { value: "Europe/Athens", label: "(UTC+02:00) Athens" },
  { value: "Europe/Belgrade", label: "(UTC+01:00) Belgrade" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Berlin" },
  { value: "Europe/Brussels", label: "(UTC+01:00) Brussels" },
  { value: "Europe/Bucharest", label: "(UTC+02:00) Bucharest" },
  { value: "Europe/Budapest", label: "(UTC+01:00) Budapest" },
  { value: "Europe/Copenhagen", label: "(UTC+01:00) Copenhagen" },
  { value: "Europe/Dublin", label: "(UTC+00:00) Dublin" },
  { value: "Europe/Helsinki", label: "(UTC+02:00) Helsinki" },
  { value: "Europe/Kiev", label: "(UTC+02:00) Kyiv" },
  { value: "Europe/Lisbon", label: "(UTC+00:00) Lisbon" },
  { value: "Europe/London", label: "(UTC+00:00) London" },
  { value: "Europe/Madrid", label: "(UTC+01:00) Madrid" },
  { value: "Europe/Moscow", label: "(UTC+03:00) Moscow" },
  { value: "Europe/Oslo", label: "(UTC+01:00) Oslo" },
  { value: "Europe/Paris", label: "(UTC+01:00) Paris" },
  { value: "Europe/Prague", label: "(UTC+01:00) Prague" },
  { value: "Europe/Rome", label: "(UTC+01:00) Rome" },
  { value: "Europe/Stockholm", label: "(UTC+01:00) Stockholm" },
  { value: "Europe/Vienna", label: "(UTC+01:00) Vienna" },
  { value: "Europe/Warsaw", label: "(UTC+01:00) Warsaw" },
  { value: "Europe/Zurich", label: "(UTC+01:00) Zurich" },

  // Pacific
  { value: "Pacific/Auckland", label: "(UTC+12:00) Auckland" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji" },
  { value: "Pacific/Guam", label: "(UTC+10:00) Guam" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Honolulu (Hawaii)" },
  { value: "Pacific/Samoa", label: "(UTC-11:00) Samoa" },
  { value: "Pacific/Tahiti", label: "(UTC-10:00) Tahiti" },
];
